### ISSUE TITLE
Ocultar los parámetros una vez que se ejecutó el algoritmo.

### ISSUE THREAD

**Issue by ccarral** [Jackelino/potro-horario-universitario#10]
Una vez ejecutado el algoritmo, se pueden esconder los siguientes parámetros:
* Selección de grupos
* Selección de materias
* Materias Libres
* Número de materias inscritas

Agregar botón de cambiar parámetros que regrese todo a como estaba antes de correr el algoritmo

**Comment by Jackelino** [comment]
se agrega la funcionalidad
