### ISSUE TITLE
Permitir que los archivos cargados en UploadFile.vue persistan en la instancia después de que se cambie de vista.

### ISSUE THREAD

**Issue by ccarral** [Jackelino/potro-horario-universitario#4]
## Descripción de las condiciones actuales
Cuando se carga un archivo en la vista UploadFile.vue, el objeto archivo se guarda en la propiedad listFile del componente.
Esto no nos permite hacer el procesamiento posterior necesario del .csv para hacer uso de los contenidos en la vista Dashboard.vue.

## Posible solución
Idealmente, la lista de archivos se debería de manejar en un store, como [Pinia](https://pinia.vuejs.org/) que nos permita volverlos a obtener y procesar desde Dashboard.vue

**Comment by Jackelino** [comment]
**Solución**

Se implemento Pinia para el manejo de la store, siendo así que en la vista UploadFile se guarda el arreglo de archivos cargados en la store.
